### ISSUE TITLE
Uncaught (in promise) Error: Unable to resolve specifier '__x00__react/jsx-dev-runtime' imported from http://localhost:5173/src/App.tsx

### ISSUE THREAD

**Issue by scc02** [gioboa/vite-module-federation#5]
Hi, @gioboa , Thank you for the work.
I am trying configure this plugin work with `vite` `react`, but, seems not work,Could you help me make it work or  provide a demo?

![image](https://user-images.githubusercontent.com/22486446/197683280-18ca44e0-bf47-42c4-8d99-9ccf2c2d7aa4.png)

below is my config repository
https://github.com/ShiChenCong/native-federation

**Comment by gioboa** [comment]
Yes, I can prepare a react example

**Comment by gioboa** [comment]
@ShiChenCong 
In [this repo](https://github.com/gioboa/react-microfrontend-demo) I created a working example.
In the remote app I used _css in js_ approach to prevent extra css files to download.
It works with _preview_ mode and in _dev_ mode as well.
In _dev_ mode we have _HMR_ feature.

Commands from the root folder:
npm run install:deps

_dev_
terminal 1: host:dev
terminal 2: remote:dev

_preview_
terminal 1: host:preview
terminal 2: remote:preview

**Comment by scc02** [comment]
Thankyou for the work
